### ISSUE TITLE
Vagrant, VirtualBox, and NAT

### ISSUE THREAD

**Issue by martinb3** [mwrock/kitchen-nodes#1]
Hello! Could you go into some detail about what kitchen driver you're using with this provisioner? It looks like this driver requires the ability to ping each guest from the host. For kitchen-vagrant and virtualbox, the most common setup by far, the default networking mode appears to be NAT, which will fail the ping check in this provisioner.

Aside: I'm also seeing node json files with 'null' for the ip address. Probably isn't good to have nodes with null for ip addresses -- it might be better if the file wasn't generated.

This all might be worth documenting in the README.

**Comment by martinb3** [comment]
Another thing I'm noticing is that with VirtualBox and NAT, every node I spin up has the same local IP:

```
root@master-ubuntu-1404:~# ifconfig eth0 | grep inet
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe0c:413e/64 Scope:Link
```

```
# ifconfig eth0 | grep inet 
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe0c:413e/64 Scope:Link
```

Perhaps on Windows this works differently, and so it isn't a big deal for your use case. I'd love to use this on Linux as well though :)

**Comment by mwrock** [comment]
Hi. I really should add this to the readme. So to get around the vagrant/virtualbox/nat issue, there are two things you need:
- add this to your driver config:
```
    network:
      - ["private_network", { type: "dhcp" }]
```
- Crreate a recipe with the following code and make sure it is at the top of your runlist. I plan to be putting this up on the supermarket this weekend:

```
# linux
if node["virtualization"] && node["virtualization"]["system"] == "vbox"
  interface = node["network"]["interfaces"].select {|key| puts key;key == "eth1"}
  unless interface.empty?
    interface["eth1"]["addresses"].each do |ip, params|
      if params['family'] == ('inet')
        node.automatic["ipaddress"] = ip
      end
    end
  end
# windows
elsif node["kernel"] && node["kernel"]["cs_info"] && node["kernel"]["cs_info"]["model"] == "VirtualBox"
  interfaces = node["network"]["interfaces"]
  interface_key = interfaces.keys.last
  node.automatic["ipaddress"] = interfaces[interface_key]["configuration"]["ip_address"][0]
end
```
