### ISSUE TITLE
kitchen-nodes provisioner needs kitchen-sync sftp finder

### ISSUE THREAD

**Issue by martin3ast** [mwrock/kitchen-nodes#10]
Hi, mwrock, thanks for this project, very useful! 

I'm working with the kitchen-sync sftp transport (https://github.com/coderanger/kitchen-sync) and this nodes provisioner.

Relevant kitchen yml snippets

```
driver: vagrant
transport:
  name: sftp
provisioner:
  name: nodes
```

Versions of gems
````
kitchen-nodes (0.6.3)
kitchen-sync (2.1.0)
kitchen-vagrant (0.19.0)
test-kitchen (1.4.2)
```

Kitchen converge fails with:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [cannot load such file -- kitchen/provisioner/finder/sftp]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Looks like we need a new sftp and rsync finder. I've put an sftp one together based on ssh, which seems to work fine... I'll submit a PR for your review

**Comment by mwrock** [comment]
sounds great!

**Comment by coderanger** [comment]
The existing finder is probably fine, it just needs to recognize subclasses of the SSH transport as being SSH-y.

**Comment by mwrock** [comment]
Ah right. I hadn't looked deep enough to note it derived from ssh

**Comment by martin3ast** [comment]
Yes, I agree that's a neater approach. Here's a modified finder.rb that looks for Ssh superclasses, that I could submit?

```
module Kitchen
  module Provisioner
    # Locates active IPs that are not localhost
    # there are separate implementations for
    # different kitchen transports
    module Finder
      def self.for_transport(transport, state)

        # Detect Ssh subclasses, e.g rsync, sftp. 
        superclass_transport_string = transport.class.superclass.name.split('::').last
        if superclass_transport_string == 'Ssh'
          transport_string = superclass_transport_string
        else
          transport_string = transport.class.name.split('::').last
        end

        require("kitchen/provisioner/finder/#{transport_string.downcase}")

        connection = transport.connection(state)
        klass = const_get(transport_string)
        object = klass.new(connection)
        object
      end
    end
  end
end
```

**Comment by mwrock** [comment]
I changed it up just a bit. The finders now register themselves against a transport and the first one whose registered transport either matches or is a superclass of the current transport wins. I published a dev gem 0.6.4.dev. Give that a go and let me know how it works. Thanks!

**Comment by mwrock** [comment]
see 76cfa93feedea01e09f849cf98af0607ac2cd5a1

**Comment by martin3ast** [comment]
Thanks, this is working well with kitchen-sync sftp transport. I've not tested rsync transport, or winrm finder.

**Comment by mwrock** [comment]
Should work for both. of those. Running kitchen on windows for sanity (ubuntu passed last night) and will push release gem for 0.6.4. Thanks for bringing this up!
