### ISSUE TITLE
policyfile support

### ISSUE THREAD

**Issue by scopenco** [mwrock/kitchen-nodes#14]
Hello,

do you plan to support policyfile in kitchen-nodes like policyfile_zero provisioner?

**Comment by mwrock** [comment]
I don't have plans to add it but would happily accept PRs that came in for that. I know thats kind of a lame response but I dont actively use this gem anymore on my "day job" but I do actively support breakages and PRs.

**Comment by legal90** [comment]
This request is not actual anymore, since Policyfile support has been merged to the built-in `chef_zero` provisioner, so it should work "out-of-box" with `nodes` provisioner too.
https://github.com/test-kitchen/test-kitchen/pull/1014

**Comment by rneu31** [comment]
@legal90 @mwrock I am using policyfiles. The "normal" and "run_list" entries in the node json file are empty. Is this because the kitchen.yml file itself does not have anything listed there (since the Policyfile controls it)?

**Comment by scopenco** [comment]
You can use my plugin, it save all json node file to nodes_path 
https://github.com/scopenco/kitchen-chefzero-nodes
