### ISSUE TITLE
help request with testing

### ISSUE THREAD

**Issue by johnsmyth** [mwrock/kitchen-nodes#17]
I'm working on a PR to add support for windows 2008R2 (https://github.com/johnsmyth/kitchen-nodes/tree/add_win2008r2_support).  It seems to work, however the servspec tests fail because node[:ip_address] is an array instead of a single ip.  I can change the tests, but wanted to make sure that I should first- i.e. that the fact multiple ip addresses in node[:ip_address] is valid and not some bug I introduced.  

There is also a failing test for a hostname that is failing( : its(:stdout) { should_not match(/#{Regexp.quote(fqdn)}/) } ) but I'm not sure of the purpose of the test?

Btw you need 1.7.2 of the winrm gem to run this on windows 2008r2 or you get an "illegal quoting on line 1" error.

**Comment by mwrock** [comment]
Thanks for adding support to 2008R2! I really would not try to support both `ipconfig` and `get-netipconfiguration` because `ipconfig` will work for both and using a single code path is simpler.

I dont **think** node[:ip_address] should return an array. I'd look to see what all the different array elements include and see if they look legitimate or not.

**Comment by johnsmyth** [comment]
FYI - the node[:ip_address] contained an array that included all the non-localhost ip addresses. The reason was because the firewall is on on that box, and the test for reachability used Net:Ping:External.  I added tests for the ssh and winrm ports and that resolved that issue for me.  I still have one test failing though, and I'm not sure the purpose of the test:
 1) other node Command "hostname" stdout should not match /vagrant\-2008R2/
            Failure/Error: its(:stdout) { should_not match(/#{Regexp.quote(fqdn)}/) }
       expected "vagrant-2008R2\n" not to match /vagrant\-2008R2/

Can you tell me what this is testing, and what I should be expecting?

**Comment by mwrock** [comment]
Its ensuring that `fqdn` wich is the fqdn of the "other node" is not the same as the hostname of the node under test.

**Comment by johnsmyth** [comment]
Is it a problem if they have the same name?  Is there something in the provisioner that should be changing the hostname?  My 2008 vms have the same name, but the other do not: 
```
ILNP-37KG8WN-MBs-MacBook-Pro:kitchen-nodes jsmyth$ kitchen exec -c hostname
-----> Execute command on node1-ubuntu-1204.
       node1-ubuntu-1204
-----> Execute command on node1-windows-2012R2.
       WIN-SGQ0RBF7LLG
-----> Execute command on node1-windows-2008R2.
       vagrant-2008R2
-----> Execute command on node2-ubuntu-1204.
       node2-ubuntu-1204
-----> Execute command on node2-windows-2012R2.
       WIN-FVUFNV1THEB
-----> Execute command on node2-windows-2008R2.
       vagrant-2008R2
```

**Comment by mwrock** [comment]
yeah thats fine. The base box probably was not sysprepped and is getting the same hostname on every provision but does not match real world problems. As long as it passes on the other platforms I think we are good.

**Comment by johnsmyth** [comment]
Sounds good.  I submitted a PR for my changes.  Thanks for patiently answering all my questions!
