### ISSUE TITLE
Working Example: Nginx Balancer + 2 App Nodes

### ISSUE THREAD

**Issue by styk-tv** [mwrock/kitchen-nodes#22]
Hi Matt

I have built an example of Nodes provisioner based on TestKitchen. Basic idea is of course to demo how to obtain the IPs of the nodes so balancer can do round-robin. Single liner where you can observe how all elements fit into place. If you approve, I will create pull request here so we can demo fully working example of Nodes.

For now example is living here:
https://bitbucket.org/styktv/chef.cookbook.nginx_balancer

Cheers,
Peter

**Comment by mwrock** [comment]
A end to end example is great! Ideally, this would live in its own github repo and the kitchen-nodes readme could reference it.

**Comment by styk-tv** [comment]
HI Matt,

I'll leave this repo where it is then. You're welcome to add a link to that
repo.
https://bitbucket.org/styktv/chef.cookbook.nginx_balancer

Cheers. Node provisioner is great :)

All the best.

Peter
